name: 'Aggregate Polls Data'
description: 'Aggregates all polls ID, title, type and tags into a single JSON file'
inputs:
  network:
    description: 'The network the polls are from, either mainnet or tenderly'
    required: true
    default: 'mainnet'
  tags-file:
    description: 'Path to the poll tags mapping file'
    required: true
    default: 'governance/polls/meta/poll-tags.json'
  output-file:
    description: 'Name of the aggregated file to be pushed to the repo'
    required: true
  hash-file:
    description: 'Name of the file containing the hash of the output-file'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
